from typing import Protocol

from app.domain.entities.persona import PersonaEntity


class PersonaRepository(Protocol):
    def list_personas(self) -> list[PersonaEntity]: ...
    def get_persona_by_id(self, persona_id: str) -> PersonaEntity | None: ...
    def add_persona(self, persona: PersonaEntity) -> PersonaEntity: ...
    def update_persona(
        self, persona_id: str, novos_dados: dict[str, object]
    ) -> PersonaEntity | None: ...
    def delete_persona(self, persona_id: str) -> bool: ...
