from typing import Protocol

from app.domain.entities.prompt import PromptEntity


class PromptRepository(Protocol):
    def list_prompts(self) -> list[PromptEntity]: ...
    def get_prompt_by_id(self, prompt_id: str) -> PromptEntity | None: ...
    def create_prompt(self, prompt: PromptEntity) -> PromptEntity: ...
    def update_prompt(self, prompt_id: str, prompt: PromptEntity) -> PromptEntity | None: ...
