from typing import Protocol

from app.domain.entities.reference_prompt import ReferencePromptEntity


class ReferencePromptRepository(Protocol):
    def listar_prompts_referencia(self) -> list[ReferencePromptEntity]: ...
    def obter_prompt_por_id(self, prompt_id: str) -> ReferencePromptEntity | None: ...
    def adicionar_prompt_referencia(
        self, prompt: ReferencePromptEntity
    ) -> ReferencePromptEntity: ...
    def atualizar_prompt_referencia(
        self, prompt_id: str, novos_dados: dict[str, object]
    ) -> ReferencePromptEntity | None: ...
    def deletar_prompt_referencia(self, prompt_id: str) -> bool: ...
